export interface SubcategoryOption {
  value: string;
  label: string;
}

export interface ProductTypeOption {
  value: string;
  label: string;
  subcategories: SubcategoryOption[];
}

export const PRODUCT_TYPE_OPTIONS: ProductTypeOption[] = [
  { 
    value: "please_select", 
    label: "Lütfen bir değer seçin.",
    subcategories: [] 
  },
  { 
    value: "footwear", 
    label: "AYAKKABI",
    subcategories: [
      { value: "baby_shoes", label: "BEBEK AYAKKABILARI" },
      { value: "children_shoes", label: "ÇOCUK AYAKKABI" },
      { value: "adult_shoes", label: "YETİŞKİN AYAKKABI" },
      { value: "other_footwear", label: "DİĞER ÜRÜNLER" }
    ]
  },
  { 
    value: "childcare_products", 
    label: "ÇOCUK KULLANIM VE BAKIM ÜRÜNLERİ",
    subcategories: [
      { value: "training_cups", label: "ALIŞTIRMA BARDAĞI VE KAPAĞI" },
      { value: "baby_carriers", label: "ASKILI TAŞIYICILAR" },
      { value: "baby_bottles", label: "BİBERON, BİBERON BAŞLIĞI VE KAPAĞI" },
      { value: "cribs_and_beds", label: "ÇOCUK KARYOLASI VE BEŞİKLER" },
      { value: "high_chairs", label: "ÇOCUKLAR İÇİN YÜKSEK SANDALYELER" },
      { value: "other_childcare", label: "DİĞER ÜRÜNLER" },
      { value: "pacifiers", label: "EMZİK" },
      { value: "pacifier_clips", label: "EMZİK BAĞLAYICILAR" },
      { value: "nursing_pillows", label: "EMZİRME YASTIĞI" },
      { value: "home_cribs", label: "EVLERDE KULLANILAN SABİT VE KATLANABİLEN ÇOCUK KARYOLALARI" },
      { value: "toilet_seat_reducers", label: "KLOZET DARALTICILAR" },
      { value: "baby_bibs", label: "MAMA ÖNLÜKLERİ" },
      { value: "stools", label: "TABURELER" },
      { value: "portable_baby_beds", label: "TAŞINABİLİR BEBEK YATAKLARI VE DESTEKLERİ" },
      { value: "strollers", label: "TEKERLEKLİ ÇOCUK ARABALARI" },
      { value: "baby_walkers", label: "YÜRÜTEÇLER" }
    ]
  },
  { 
    value: "detergents", 
    label: "DETERJANLAR",
    subcategories: [
      { value: "dish_detergent", label: "BULAŞIK DETERJANI" },
      { value: "laundry_detergent", label: "ÇAMAŞIR DETERJANI" },
      { value: "bleach", label: "ÇAMAŞIR SUYU" },
      { value: "fabric_softener", label: "ÇAMAŞIR YUMUŞATICISI" },
      { value: "other_detergents", label: "DİĞER" },
      { value: "general_cleaning", label: "GENEL TEMİZLİK ÜRÜNLERİ" },
      { value: "limescale_remover", label: "KİREÇ ÇÖZÜCÜ" },
      { value: "drain_opener", label: "LAVABO AÇICI" },
      { value: "hydrochloric_acid", label: "TUZ RUHU" },
      { value: "grease_remover", label: "YAĞ ÇÖZÜCÜ" }
    ]
  },
  { 
    value: "other_consumer_products", 
    label: "DİĞER TÜKETİCİ ÜRÜNLERİ",
    subcategories: [
      { value: "sports_equipment", label: "BİSİKLET, GOLF SOPALARI, RAKETLER GİBİ SPOR EKİPMANLARI,KASKLAR,PATENLER?" },
      { value: "lighters", label: "ÇAKMAKLAR" },
      { value: "other_products", label: "DİĞER ÜRÜNLER" },
      { value: "hand_tools", label: "EL ALETLERİ" },
      { value: "laser_pointers", label: "LAZER İŞARETLEYİCİLER" },
      { value: "furniture", label: "MOBİLYA" },
      { value: "candles", label: "MUMLAR" },
      { value: "playground_equipment", label: "OYUN ALANI ELEMANLARI VE DIŞ MEKÂN MOBİLYALARI" },
      { value: "blinds", label: "STOR PERDELER" },
      { value: "jewelry", label: "TAKILAR" },
      { value: "food_imitation_bathroom", label: "YİYECEK TAKLİDİ ÜRÜNLER (BANYO ÜRÜNLERİ)" },
      { value: "food_imitation_decorative", label: "YİYECEK TAKLİDİ ÜRÜNLER (DEKORATİF EŞYALAR)" },
      { value: "food_imitation_candles", label: "YİYECEK TAKLİDİ ÜRÜNLER (DEKORATİF MUMLAR)" },
      { value: "food_imitation_magnets", label: "YİYECEK TAKLİDİ ÜRÜNLER (MIKNATISLI ÜRÜNLER)" },
      { value: "food_imitation_expanding", label: "YİYECEK TAKLİDİ ÜRÜNLER (OYUNCAKLAR DIŞINDA KALAN SUDA GENİŞLEYEN ÜRÜNLER)" }
    ]
  },
  { 
    value: "toothbrushes", 
    label: "DİŞ FIRÇALARI",
    subcategories: [
      { value: "interdental_brushes", label: "ARAYÜZ FIRÇALARI" },
      { value: "other_toothbrushes", label: "DİĞER ÜRÜNLER" },
      { value: "regular_toothbrushes", label: "DİŞ FIRÇALARI" },
      { value: "electric_toothbrush_heads", label: "ELEKTRİKLE/PİLLE ÇALIŞAN DİŞ FIRÇALARININ FIRÇA BAŞLIKLARI" }
    ]
  },
  { 
    value: "electrical_equipment", 
    label: "ELEKTRİKLİ EKİPMANLAR",
    subcategories: [
      { value: "3d_printer", label: "3 BOYUTLU YAZICI" },
      { value: "adapter", label: "ADAPTÖR" },
      { value: "battery_charger", label: "AKÜ ŞARJ CİHAZI" },
      { value: "aquarium_equipment", label: "AKVARYUMLAR VE BAHÇE HAVUZLARINDA KULLANILAN ELEKTRİKLİ CİHAZLAR (HAVALANDIRICILAR, AKVARYUM ISITICILARI, OTOMATİK YEM DAĞITICILAR, ÇAMUR EMME CİHAZLARI)" },
      { value: "alarm_device", label: "ALARM CİHAZI" },
      { value: "alarm_recorder", label: "ALARM KAYIT CİHAZI" },
      { value: "alarm_control_mechanism", label: "ALARM KUMANDA MEKANİZMASI" },
      { value: "alarm_panel", label: "ALARM PANELİ" },
      { value: "low_voltage_motor_starters", label: "ALÇAK GERİLİM MOTOR YOL VERİCİLERİ" },
      { value: "amplified_sound_system", label: "AMFİLİ SES SİSTEMİ" },
      { value: "amplifier", label: "AMPLİFİKATÖR (SES YÜKSELTİCİSİ)" },
      { value: "bulb", label: "AMPUL(ENERJİ TASARRUFLU,FLORESAN LAMBA,LED AMPUL)" },
      { value: "switch", label: "ANAHTAR/SWİTCH" },
      { value: "instant_water_heater", label: "ANİ SU ISITICI (ŞOFBEN)" },
      { value: "antenna_amplifier", label: "ANTEN YÜKSELTİCİ" },
      { value: "arc_lamp", label: "ARK LAMBASI" },
      { value: "lighting_fixture", label: "ARMATÜR (AVİZE,GECE LAMBASI, MASA LAMBASI, APLİK, VB.)" },
      { value: "extractor_hood", label: "ASPİRATÖR" },
      { value: "lighting_element", label: "AYDINLATMA ELEMANI (BALAST,DUY,STARTER)" },
      { value: "connection_cables", label: "BAĞLANTI KABLOLARI(TELEVİZYON ALICILARI İÇİN)" },
      { value: "copper_conductors", label: "BAKIR, BAKIR İLETKENLER VE BAKIR TELLER (EMAYE BOBİN TELİ)" },
      { value: "barcode_reader", label: "BARKOD OKUYUCU" },
      { value: "barcode_printer", label: "BARKOD YAZICISI" },
      { value: "printing_machine", label: "BASKI MAKİNESİ" },
      { value: "digital_printing_machine", label: "BASKI MAKİNESİ/DİJİTAL" },
      { value: "baby_monitor", label: "BEBEK TELSİZİ" },
      { value: "bottle_warmer", label: "BİBERON ISITICI" },
      { value: "information_processing_unit", label: "BİLGİ İŞLEM BİRİMİ/ÜNİTESİ" },
      { value: "computer_motherboard", label: "BİLGİSAYAR ANA KARTI" },
      { value: "computer_memory", label: "BİLGİSAYAR BELLEK BİRİMİ (RAM)" },
      { value: "computer_graphics_card", label: "BİLGİSAYAR EKRAN KARTI" },
      { value: "computer_fan", label: "BİLGİSAYAR FANI" },
      { value: "computer_power_supply", label: "BİLGİSAYAR GÜÇ KAYNAĞI" },
      { value: "webcam", label: "BİLGİSAYAR KAMERASI/WEB KAMERASI/WEB CAM" },
      { value: "computer_case", label: "BİLGİSAYAR KASASI" },
      { value: "computer_sound_card", label: "BİLGİSAYAR SES KARTI" },
      { value: "computer_tv_card", label: "BİLGİSAYAR TELEVİZYON KARTI/TV KARTI" },
      { value: "single_phase_induction_motors", label: "BİR FAZLI ENDÜKSİYON MOTORLARI" },
      { value: "blender", label: "BLENDER" },
      { value: "bluetooth_flash_drive", label: "BLUETOOTH FLASH BELLEK" },
      { value: "insect_killing_devices", label: "BÖCEK ÖLDÜRME CİHAZLARI" },
      { value: "steam_cooker", label: "BUHARLI PİŞİRİCİ" },
      { value: "steam_cleaners", label: "BUHARLI TEMİZLEYİCİLER" },
      { value: "steam_iron", label: "BUHARLI ÜTÜ (ÜTÜ)" },
      { value: "button", label: "BUTON" },
      { value: "capture_card", label: "CAPTURA KARTI" },
      { value: "cd_player", label: "CD PLAYER (CD OYNATICI)" },
      { value: "cd_drive", label: "CD SÜRÜCÜ" },
      { value: "pocket_computer", label: "CEP BİLGİSAYARI" },
      { value: "skin_analyzer", label: "CİLT ANALİZ CİHAZI" },
      { value: "skin_care_set", label: "CİLT BAKIM SETİ" },
      { value: "skin_vacuum_device", label: "CİLT VAKUM CİHAZI(GÜZELLİK MERKEZLERİNDE KULLANILAN)" },
      { value: "tea_maker", label: "ÇAY MAKİNESİ/SETİ" },
      { value: "soup_warmer", label: "ÇORBA ISITICI" },
      { value: "extractor_hood", label: "DAVLUMBAZ" },
      { value: "drum_oven", label: "DAVUL FIRIN" },
      { value: "freezer", label: "DERİN DONDURUCU" },
      { value: "revolution_counter", label: "DEVİR SAYACI" },
      { value: "circuit_breaker", label: "DEVRE KESİCİ/CİRCUİT BREAKER" },
      { value: "intercom", label: "DİAFON" },
      { value: "digital_camera", label: "DİGİTAL KAMERA" },
      { value: "digital_photo_frame", label: "DİJİTAL FOTOĞRAF ÇERÇEVESİ" },
      { value: "digital_camera", label: "DİJİTAL FOTOĞRAF MAKİNESİ" },
      { value: "toothbrush_machine", label: "DİŞ FIRÇASI MAKİNESİ" },
      { value: "dvd_player", label: "DVD ÇALAR/DVD PLAYER" },
      { value: "dvd_receiver", label: "DVD RECEİVER" },
      { value: "dvd_drive", label: "DVD SÜRÜCÜ" },
      { value: "dvd_writer", label: "DVD WRİTER (YAZICI)" },
      { value: "toaster", label: "EKMEK KIZARTMA MAKİNESİ" },
      { value: "bread_maker", label: "EKMEK YAPIM MAKİNESİ" },
      { value: "flashlight", label: "EL FENERİ" },
      { value: "hand_dryer", label: "EL KURUTMA MAKİNESİ" },
      { value: "electric_motor_ac", label: "ELEKTRİK MOTORU (AC)" },
      { value: "electric_motor_dc", label: "ELEKTRİK MOTORU (DC)" },
      { value: "electrical_panel", label: "ELEKTRİK PANOSU" },
      { value: "vacuum_cleaner", label: "ELEKTRİK SÜPÜRGESİ" },
      { value: "rechargeable_vacuum_cleaner", label: "ELEKTRİK SÜPÜRGESİ (ŞARJLI)" },
      { value: "electric_foot_warmer", label: "ELEKTRİKLİ AYAK ISITICISI" },
      { value: "electric_fish_catching_machines", label: "ELEKTRİKLİ BALIK YAKALAMA MAKİNELERİ" },
      { value: "electric_blanket", label: "ELEKTRİKLİ BATTANİYE" },
      { value: "electric_knife", label: "ELEKTRİKLİ BIÇAK" },
      { value: "electric_knife_sharpener", label: "ELEKTRİKLİ BIÇAK BİLEYİCİ" },
      { value: "electric_tea_cauldron", label: "ELEKTRİKLİ ÇAY KAZANI" },
      { value: "electric_fence_power_circuits", label: "ELEKTRİKLİ ÇİT GÜÇ DEVRELERİ" },
      { value: "electric_oven", label: "ELEKTRİKLİ FIRIN" },
      { value: "electric_towel_machines", label: "ELEKTRİKLİ HAVLU MAKİNELERİ" },
      { value: "electric_heater", label: "ELEKTRİKLİ ISITICI" },
      { value: "electric_paper_towel_machine", label: "ELEKTRİKLİ KAĞIT HAVLU MAKİNESİ" },
      { value: "electric_combi_boiler", label: "ELEKTRİKLİ KOMBİ" },
      { value: "electric_exercise_bike", label: "ELEKTRİKLİ KONDİSYON BİSİKLETİ" },
      { value: "electric_treadmill", label: "ELEKTRİKLİ KOŞU BANDI" },
      { value: "electric_room_heater", label: "ELEKTRİKLİ ODA ISTICISI" },
      { value: "electric_organ", label: "ELEKTRİKLİ ORG" },
      { value: "electric_cooking_device", label: "ELEKTRİKLİ PİŞİRME CİHAZI" },
      { value: "electric_pizza_pan", label: "ELEKTRİKLİ PİZZA TAVA" },
      { value: "electric_radiator", label: "ELEKTRİKLİ RADYATÖR" },
      { value: "electric_sound_or_visual_signal_devices", label: "ELEKTRİKLİ SES VEYA GÖRÜNTÜLÜ İŞARET CİHAZLARI" },
      { value: "electric_insect_screen", label: "ELEKTRİKLİ SİNEKLİK" },
      { value: "electric_sterilizer", label: "ELEKTRİKLİ STERİLİZATÖR" },
      { value: "electric_kettle", label: "ELEKTRİKLİ SU ISITICISI (KETTLE)" },
      { value: "electric_water_heater", label: "ELEKTRİKLİ ŞOFBEN" },
      { value: "electric_water_heater_with_tank", label: "ELEKTRİKLİ ŞOFBEN (DEPOLU TERMOSİFON)" },
      { value: "electric_plate_warmer", label: "ELEKTRİKLİ TABAK ISITICI" },
      { value: "electric_nail_dryer", label: "ELEKTRİKLİ TIRNAK KURUTUCU" },
      { value: "electric_christmas_decoration", label: "ELEKTRİKLİ YILBAŞI SÜSÜ" },
      { value: "electro_guitar_set", label: "ELEKTRO GİTAR SET" },
      { value: "electronic_board", label: "ELEKTRONİK BOARD (YAZI TAHTASI)" },
      { value: "electronic_card", label: "ELEKTRONİK KART" },
      { value: "electronic_toilet_lid", label: "ELEKTRONİK KLOZET KAPAĞI" },
      { value: "electronic_eraser", label: "ELEKTRONİK SİLGİ" },
      { value: "infrared_ultraviolet_devices", label: "ENFRARUJ VE ULTRAVİOLE CİHAZLAR (DERİYE UYGULAMAK İÇİN)" },
      { value: "epilation_device", label: "EPİLASYON ALETİ" },
      { value: "ethernet_card", label: "ETHERNET KARTI" },
      { value: "outdoor_food_cooler", label: "EV DIŞI GIDA SOĞUTUCU" },
      { value: "home_theater_system", label: "EV SİNEMA SETİ" },
      { value: "home_bain_marie", label: "EV TİPİ BENMARİ MAKİNELERİ" },
      { value: "home_sharpening_machine", label: "EV TİPİ BİLEYLEME MAKİNESİ" },
      { value: "home_steam_station_irons", label: "EV TİPİ BUHAR İSTASYONLU ÜTÜLER" },
      { value: "home_steam_machine", label: "EV TİPİ BUHAR MAKİNESİ" },
      { value: "home_steam_cleaning_machine", label: "EV TİPİ BUHAR TEMİZLEME MAKİNESİ" },
      { value: "home_dishwasher", label: "EV TİPİ BULAŞIK MAKİNESİ" },
      { value: "home_ice_machine", label: "EV TİPİ BUZ MAKİNESİ" },
      { value: "home_refrigerators", label: "EV TİPİ BUZDOLAPLARI" },
      { value: "home_clothes_dryer", label: "EV TİPİ ÇAMAŞIR KURUTMA MAKİNELERİ" },
      { value: "home_washing_machines", label: "EV TİPİ ÇAMAŞIR MAKİNELERİ" },
      { value: "home_chocolate_machine", label: "EV TİPİ ÇİKOLATA MAKİNESİ" },
      { value: "home_garbage_disposal", label: "EV TİPİ ÇÖP ÖĞÜTÜCÜ" },
      { value: "home_outdoor_unit", label: "EV TİPİ DIŞ ÜNİTE" },
      { value: "home_sewing_machine", label: "EV TİPİ DİKİŞ MAKİNESİ" },
      { value: "home_slicing_machine", label: "EV TİPİ DİLİMLEME MAKİNESİ" },
      { value: "home_electric_can_opener", label: "EV TİPİ ELEKTRİKLİ KONSERVE AÇACAĞI" },
      { value: "home_electric_water_pump", label: "EV TİPİ ELEKTRİKLİ SU POMPASI" },
      { value: "home_meat_grinder", label: "EV TİPİ ET KIYMA MAKİNESİ" },
      { value: "home_indoor_unit", label: "EV TİPİ İÇ ÜNİTE" },
      { value: "home_coffee_grinder", label: "EV TİPİ KAHVE ÖĞÜTME MAKİNESİ" },
      { value: "home_air_conditioners", label: "EV TİPİ KLİMALAR (İÇ VE DIŞ ÜNİTE BİRLİKTE)" },
      { value: "home_washer_dryer_combo", label: "EV TİPİ KURUTMALI ÇAMAŞIR MAKİNELERİ" },
      { value: "home_pasta_machine", label: "EV TİPİ PASTA MAKİNESİ" },
      { value: "home_silicone_gun", label: "EV TİPİ SİLİKON TABANCASI" },
      { value: "home_candy_machine", label: "EV TİPİ ŞEKERLEME MAKİNESİ" },
      { value: "home_submersible_pump", label: "EV VE BENZERİ YERLERDE KULLANILAN DALGIÇ POMPA" },
      { value: "home_circulation_pump", label: "EV VE BENZERİ YERLERDE KULLANILAN DEVİRDAİM POMPASI" },
      { value: "home_digital_scale", label: "EVDE KULLANILAN DİGİTAL BASKÜL" },
      { value: "paper_shredder", label: "EVRAK İMHA MAKİNESİ" },
      { value: "fax_machine", label: "FAKS MAKİNASI" },
      { value: "fan", label: "FAN" },
      { value: "filter", label: "FİLTRE" },
      { value: "plug", label: "FİŞ" },
      { value: "plug_and_socket_group", label: "FİŞ VE PRİZ (GRUP)" },
      { value: "usb_flash_drive", label: "FLASH DİSK (USB BELLEK)" },
      { value: "camera", label: "FOTOĞRAF MAKİNESİ" },
      { value: "photocopier", label: "FOTOKOPİ MAKİNESİ" },
      { value: "frequency_converter", label: "FREKANS KONVERTER" },
      { value: "frequency_booster", label: "FREKANS YÜKSELTİCİ" },
      { value: "deep_fryer", label: "FRİTÖZ (KIZARTMA MAKİNESİ)" },
      { value: "garage_door_remote", label: "GARAJ KAPISI KUMANDASI" },
      { value: "gas_alarm_device", label: "GAZ ALARM CİHAZI(YANICI GAZ, KARBONMONOKSİT DEDEKTÖRÜ)" },
      { value: "solar_panels", label: "GÜNEŞ PANELLERİ" },
      { value: "beauty_center_heat_blanket", label: "GÜZELLİK MERKEZLERİNDE KULLANILAN ISI BATTANİYE" },
      { value: "memory_card", label: "HAFIZA KARTI" },
      { value: "hard_disk", label: "HARD DİSK" },
      { value: "external_hard_disk", label: "HARİCİ HARD DİSK" },
      { value: "air_filter", label: "HAVA FİLTRESİ" },
      { value: "air_humidifier", label: "HAVA NEMLENDİRİCİ" },
      { value: "air_curtain", label: "HAVA PERDESİ" },
      { value: "air_purifier", label: "HAVA TEMİZLEME CİHAZI" },
      { value: "calculator", label: "HESAP MAKİNESİ" },
      { value: "speaker", label: "HOPARLÖR" },
      { value: "light_converter", label: "IŞIK DÖNÜŞTÜRÜCÜ" },
      { value: "spotlight", label: "IŞILDAK" },
      { value: "thinning_passive_gymnastic_devices", label: "İNCELTME VE PASİF CİMLASTİK CİHAZLARI" },
      { value: "inverter", label: "İNVERTÖR" },
      { value: "jacuzzi", label: "JAKUZİ" },
      { value: "joystick", label: "JOYSTİK" },
      { value: "cable", label: "KABLO" },
      { value: "cable_cutting_device", label: "KABLO KESME CİHAZI" },
      { value: "residual_current_circuit_breaker", label: "KAÇAK AKIM KORUMA ANAHTARI" },
      { value: "residual_current_relay", label: "KAÇAK AKIM ROLESİ" },
      { value: "coffee_machine", label: "KAHVE MAKİNESİ" },
      { value: "permanent_makeup_device", label: "KALICI MAKYAJ CİHAZI" },
      { value: "camera", label: "KAMERA (CAMERA)" },
      { value: "camera_control_device", label: "KAMERA KONTROL CİHAZI" },
      { value: "camera_monitor", label: "KAMERA MONİTÖRÜ (VİZÖR)" },
      { value: "door_detector", label: "KAPI DEDEKTÖRÜ" },
      { value: "door_security_system", label: "KAPI GÜVENLİK SİSTEMİ" },
      { value: "card_encoding_device", label: "KART KODLAMA CİHAZI" },
      { value: "card_reader", label: "KART OKUYUCU" },
      { value: "muscle_simulator", label: "KAS SİMİLATÖRÜ" },
      { value: "cassette_player", label: "KASETÇALAR" },
      { value: "juicer", label: "KATI MEYVE SIKACAĞI" },
      { value: "cavitation_device", label: "KAVİTASYON CİHAZI" },
      { value: "recorder", label: "KAYIT CİHAZI (RECORDER)" },
      { value: "uninterruptible_power_supply", label: "KESİNTİSİZ GÜÇ KAYNAKLARI(UPS)" },
      { value: "hair_removal_machine", label: "KIL ALMA MAKİNESİ" },
      { value: "keyboard", label: "KLAVYE (KEYBOARD)" },
      { value: "terminal_block", label: "KLEMENS (VAGO)" },
      { value: "compressor_motor", label: "KOMPRESÖR MOTORU" },
      { value: "contactor", label: "KONTAKTÖR" },
      { value: "control_device", label: "KONTROL CİHAZI/ÜNİTESİ" },
      { value: "control_card", label: "KONTROL KARTI" },
      { value: "control_keyboard", label: "KONTROL KLAVYESİ" },
      { value: "control_panel", label: "KONTROL PANELİ" },
      { value: "control_panel_general", label: "KONTROL PANOSU" },
      { value: "fire_detection_control_panel", label: "KONTROL PANOSU (YANGIN ALGILAMA)" },
      { value: "headphones", label: "KULAKLIK" },
      { value: "headphone_kit", label: "KULAKLIK KİTİ" },
      { value: "remote_control", label: "KUMANDA" },
      { value: "control_panel", label: "KUMANDA PANOSU" },
      { value: "laptop", label: "LAPTOP/NOTEBOOK/DİZÜSTÜ" },
      { value: "laser_epilation_device", label: "LAZER EPİLASYON CİHAZI" },
      { value: "laser_pointer", label: "LAZER POİNTER" },
      { value: "lcd_led_oled_monitor", label: "LCD/LED/OLED MONİTÖR" },
      { value: "led_projector", label: "LED PROJEKTÖR (BİNA AYDINLATMA)" },
      { value: "soldering_machine", label: "LEHİM MAKİNESİ" },
      { value: "soldering_gun", label: "LEHİM TABANCASI" },
      { value: "lymph_drainage_device", label: "LENF DRENAJ CİHAZI" },
      { value: "mine_detector", label: "MADEN DEDEKTÖRÜ" },
      { value: "magnetic_tape", label: "MANYETİK TEYP" },
      { value: "massage_device", label: "MASAJ ALETİ" },
      { value: "massage_belt", label: "MASAJ KEMERİ/SAUNABELT" },
      { value: "desktop_pc", label: "MASAÜSTÜ/PC)" },
      { value: "metal_detector", label: "METAL DEDEKTÖRÜ" },
      { value: "popcorn_machine", label: "MISIR PATLATMA MAKİNESİ" },
      { value: "microwave_oven", label: "MİKRODALGA FIRIN" },
      { value: "microphone", label: "MİKROFON" },
      { value: "microphone_kit", label: "MİKROFON KİTİ" },
      { value: "mixer", label: "MİKSER" },
      { value: "mini_oven", label: "MİNİ FIRIN" },
      { value: "modem", label: "MODEM" },
      { value: "motor_speed_control_device", label: "MOTOR HIZ KONTROL CİHAZI" },
      { value: "motor_driver", label: "MOTOR SÜRÜCÜSÜ" },
      { value: "mouse", label: "MOUSE/FARE" },
      { value: "mp3_mp4_player", label: "MP3/MP4 PLAYER" },
      { value: "kitchen_appliances", label: "MUTFAK MAKİNELERİ" },
      { value: "food_processor", label: "MUTFAK ROBOTU" },
      { value: "music_system", label: "MÜZİK SETİ" },
      { value: "citrus_juicer", label: "NARENCİYE SIKACAĞI" },
      { value: "navigation_device", label: "NAVİGASYON CİHAZI" },
      { value: "optical_reader", label: "OPTİK OKUYUCU" },
      { value: "automatic_room_spray", label: "OTOMATİK ODA SPREYİ" },
      { value: "game_consoles", label: "OYUN KONSOLLARI" },
      { value: "ozone_machine", label: "OZON MAKİNESİ" },
      { value: "measuring_device", label: "ÖLÇÜ ALETİ/CİHAZI" },
      { value: "money_counting_machine", label: "PARA SAYMA MAKİNESİ" },
      { value: "surge_arresters", label: "PARAFUDRLAR" },
      { value: "perfume_spraying_device", label: "PARFÜM PÜSKÜRTME CİHAZI" },
      { value: "record_player", label: "PİKAP" },
      { value: "battery_liquid_soap_dispenser", label: "PİLLİ SIVI SABUNLUK" },
      { value: "runway_lighting_system", label: "PİST AYDINLATMA SİSTEMİ" },
      { value: "plasma_heater", label: "PLAZMA ISITICI" },
      { value: "press_iron", label: "PRES ÜTÜ" },
      { value: "socket", label: "PRİZ" },
      { value: "projector", label: "PROJEKSİYON CİHAZI (PROJEKTÖR)" },
      { value: "radio", label: "RADYO" },
      { value: "pocket_radio", label: "RADYO (CEP RADYOSU)" },
      { value: "radio_cd_player", label: "RADYO CD ÇALAR" },
      { value: "radio_cassette_player", label: "RADYO KASETÇALAR" },
      { value: "reactive_power_control_units", label: "REAKTİF GÜÇ KONTROL ÜNİTELERİ" },
      { value: "rectifier", label: "REDRESÖR" },
      { value: "resistor", label: "REZİSTANS" },
      { value: "food_processor", label: "RONDO (DOĞRAYICI)" },
      { value: "router", label: "ROUTER" },
      { value: "thermal_relay", label: "RÖLE(TERMİK)" },
      { value: "fixed_home_ovens", label: "SABİT EV TİPİ FIRINLAR" },
      { value: "hair_care_device", label: "SAÇ BAKIM CİHAZI" },
      { value: "hair_clipper", label: "SAÇ KESME MAKİNESİ" },
      { value: "hair_dryer", label: "SAÇ KURUTMA MAKİNESİ" },
      { value: "hair_styling_machine", label: "SAÇ ŞEKİLLENDİRME MAKİNESİ" },
      { value: "sauna", label: "SAUNA" },
      { value: "scanner", label: "SCANNER /TARAYICI" },
      { value: "sensor", label: "SENSÖR" },
      { value: "servo_motor", label: "SERVO MOTOR" },
      { value: "sound_adjusting_device", label: "SES DÜZENLEYİCİ CİHAZ" },
      { value: "sound_recording_device", label: "SES KAYIT CİHAZI/ SİSTEMİ" },
      { value: "sound_system", label: "SES SİSTEMİ" },
      { value: "sound_device", label: "SES VERME CİHAZI" },
      { value: "level_detection_device", label: "SEVİYE TESPİT CİHAZI" },
      { value: "wax_hair_removal_machine", label: "SIR AĞDA MAKİNESİ" },
      { value: "fuse", label: "SİGORTA (W OTOMAT)" },
      { value: "siren", label: "SİREN" },
      { value: "mosquito_repellent", label: "SİVRİSİNEK KOVUCU" },
      { value: "slide_advance_remote", label: "SLAYT ATLATMA KUMANDASI" },
      { value: "cooling_motor", label: "SOĞUTMA MOTORU" },
      { value: "solarium_device", label: "SOLARYUM CİHAZI" },
      { value: "water_purifier", label: "SU ARITMA CİHAZI" },
      { value: "water_control_system", label: "SU KONTROL SİSTEMİ" },
      { value: "water_dispenser", label: "SU SEBİLİ" },
      { value: "waterbed_heater", label: "SU YATAĞI ISTICISI" },
      { value: "switch", label: "ŞALTER" },
      { value: "charger", label: "ŞARJ CİHAZI (CEP TELEFONU HARİÇ)" },
      { value: "mobile_phone_charger", label: "ŞARJ CİHAZI (CEP TELEFONU)" },
      { value: "blood_pressure_monitor", label: "TANSİYON ÖLÇER" },
      { value: "portable_immersion_water_heater", label: "TAŞINABİLİR ELEKTRİKLİ DALDIRMA TİPİ SU ISITICISI" },
      { value: "portable_electric_grill", label: "TAŞINABİLİR ELEKTRİKLİ IZGARA" },
      { value: "portable_electric_stove", label: "TAŞINABİLİR ELEKTRİKLİ OCAK" },
      { value: "portable_welding_machine", label: "TAŞINABİLİR KAYNAK MAKİNESİ" },
      { value: "lcd_television", label: "TELEVİZVON (LCD)" },
      { value: "plasma_television", label: "TELEVİZVON (PLAZMA)" },
      { value: "tube_television", label: "TELEVİZYON (TÜPLÜ)" },
      { value: "television_receiver", label: "TELEVİZYON ALICISI" },
      { value: "thermal_magnetic_compact_switch", label: "TERMİK MANYETİK KOMPAKT ŞALTER" },
      { value: "thermal_magnetic_switch", label: "TERMİK MANYETİK ŞALTER (KOMPAKT ŞALTER)" },
      { value: "thermostat", label: "TERMOSTAT" },
      { value: "test_device", label: "TEST CİHAZI/MAKİNESİ" },
      { value: "commercial_electric_boiling_pans", label: "TİCARİ ELEKTRİKLİ KAYNATMA TAVALARI(SICAK İÇECEK MAKİNALARI)" },
      { value: "toaster", label: "TOST MAKİNESİ" },
      { value: "transformer", label: "TRAFO" },
      { value: "shaver", label: "TRAŞ MAKİNESİ" },
      { value: "ultrasonic_cleaner", label: "ULTRASONİK TEMİZLEYİCİ" },
      { value: "usb_port", label: "USB PORT" },
      { value: "satellite_receiver", label: "UYDU ALICI CİHAZLARI (RECEİVER)" },
      { value: "satellite_antenna", label: "UYDU ANTENİ" },
      { value: "3d_scanner", label: "ÜÇ BOYUTLU TARAYICI" },
      { value: "three_phase_induction_motors", label: "ÜÇ FAZLI ENDÜKSİYON MOTORLARI" },
      { value: "blower_and_suction_bellows", label: "ÜFLEYİCİ VE EMİCİ KÖRÜK" },
      { value: "ironing_board", label: "ÜTÜ MASASI" },
      { value: "ventilator", label: "VANTİLATÖR" },
      { value: "facial_steamer", label: "VAPOZON" },
      { value: "vcd_player", label: "VCD OYNATICI/OKUYUCU/PLAYER" },
      { value: "video_player", label: "VİDEO GÖSTERME CİHAZI/VİDEO PLAYER" },
      { value: "video_recorder", label: "VİDEO KAYIT CİHAZI" },
      { value: "voltage_regulator", label: "VOLTAJ REGÜLATÖRÜ" },
      { value: "body_care_device", label: "VÜCUT BAKIM CİHAZI" },
      { value: "glue_gun", label: "YAPIŞTIRICI TABANCA" },
      { value: "cash_register", label: "YAZAR KASA" },
      { value: "printer_various", label: "YAZICI (LAZER YAZICI, NOKTA VURUŞLU, MÜREKKEPLİ)" },
      { value: "printer", label: "YAZICI (PRİNTER)" },
      { value: "yogurt_maker", label: "YOĞURT YAPMA MAKİNESİ" },
      { value: "egg_boiling_machine", label: "YUMURTA HAŞLAMA MAKİNASI" },
      { value: "time_clock", label: "ZAMAN SAATİ/ZAMAN ROLESİ" }
    ]
  },
  { 
    value: "food", 
    label: "GIDA",
    subcategories: [
      { value: "alcoholic_beverages", label: "ALKOLLÜ İÇECEKLER" },
      { value: "non_alcoholic_beverages", label: "ALKOLSÜZ İÇECEKLER" },
      { value: "beekeeping_products", label: "ARICILIK ÜRÜNLERİ" },
      { value: "flavors_and_additives", label: "AROMALAR VE KATKI MADDELERİ" },
      { value: "spices_and_sauces", label: "BAHARATLAR, ÇEŞNİ VERİCİLER VE SOSLAR" },
      { value: "legumes", label: "BAKLAGİLLER" },
      { value: "fish_and_seafood", label: "BALIK VE DİĞER SU ÜRÜNLERİ" },
      { value: "tea_and_coffee", label: "BİTKİ ÇAYI, SİYAH ÇAY VE KAHVE ÜRÜNLERİ" },
      { value: "vegetable_oil_and_margarine", label: "BİTKİSEL YAĞ VE MARGARİN" },
      { value: "geographical_indication_foods", label: "COĞRAFİ İŞARET ALMIŞ GIDA ÜRÜNLERİ" },
      { value: "chocolate_and_cocoa", label: "ÇİKOLATA VE KAKAO ÜRÜNLERİ" },
      { value: "meat_and_meat_products", label: "ET VE ET MAMULLERİ" },
      { value: "ready_meals", label: "HAZIR YEMEK VE YEMEK FABRİKASI (TABLDOT)" },
      { value: "imported_food_items", label: "İTHAL EDİLEN GIDA MADDELERİ" },
      { value: "nuts_and_snacks", label: "KURUYEMİŞ VE ÇEREZLER" },
      { value: "fruit_and_vegetable_processing", label: "MEYVE VE SEBZE İŞLEME" },
      { value: "special_dietary_foods", label: "ÖZEL BESLENME AMAÇLI GIDALAR" },
      { value: "pastry_and_desserts", label: "PASTACILIK ÜRÜNLERİ VE TATLILAR" },
      { value: "milk_and_dairy", label: "SÜT VE SÜT MAMULLERİ" },
      { value: "confectionery", label: "ŞEKERLİ MAMULLER" },
      { value: "grain_flour_products", label: "TAHIL, UN VE UNLU MAMULLER" },
      { value: "unclassified_foods", label: "TASNİF DIŞI GIDALAR" },
      { value: "eggs_and_egg_products", label: "YUMURTA VE YUMURTA MAMULLERİ" }
    ]
  },
  { 
    value: "food_contact_materials", 
    label: "GIDA İLE TEMAS EDEN MADDELER",
    subcategories: [
      { value: "training_cups", label: "ALIŞTIRMA BARDAKLARI" },
      { value: "bottle_nipples", label: "BİBERON BAŞLIKLARI," },
      { value: "baby_bottles", label: "BİBERON," },
      { value: "other_baby_products", label: "DİĞER BEBEK ÜRÜNLERİ" }
    ]
  },
  { 
    value: "prepackaging", 
    label: "HAZIR AMBALAJLAMA",
    subcategories: [
      { value: "alcoholic_drinks", label: "ALKOLLÜ İÇKİLER" },
      { value: "non_alcoholic_beverages", label: "ALKOLSÜZ İÇECEKLER" },
      { value: "beekeeping_products", label: "ARICILIK ÜRÜNLERİ" },
      { value: "flavors_and_additives", label: "AROMALAR VE KATKI MADDELERİ" },
      { value: "spices", label: "BAHARATLAR" },
      { value: "legumes", label: "BAKLAGİLLER" },
      { value: "fish_and_seafood", label: "BALIK VE DİĞER SU ÜRÜNLERİ" },
      { value: "plant_tea_coffee_products", label: "BİTKİ, ÇAY VE KAHVE ÜRÜNLERİ" },
      { value: "vegetable_oil_and_margarine", label: "BİTKİSEL YAĞ VE MARGARİN" },
      { value: "paints", label: "BOYALAR" },
      { value: "flavorings", label: "ÇEŞNİ VERİCİLER" },
      { value: "chocolate_and_cocoa", label: "ÇİKOLATA VE KAKAO ÜRÜNLERİ" },
      { value: "solvents", label: "ÇÖZÜCÜLER" },
      { value: "other", label: "DİĞER" },
      { value: "meat_and_meat_products", label: "ET VE ET ÜRÜNLERİ" },
      { value: "glues_and_adhesives", label: "KATI, TOZ VEYA SIVI HALİNDEKİ TUTKALLAR VE YAPIŞTIRICILAR" },
      { value: "canned_food", label: "KONSERVE" },
      { value: "canned_foods_plural", label: "KONSERVELER" },
      { value: "cosmetics", label: "KOZMETİKLER" },
      { value: "pet_dry_food", label: "KÖPEKLER VE KEDİLER İÇİN KURU GIDALAR" },
      { value: "dried_fruits_vegetables", label: "KURUTULMUŞ MEYVE SEBZE" },
      { value: "nuts_and_snacks", label: "KURUYEMİŞ VE ÇEREZLER" },
      { value: "machine_oils", label: "MAKİNA YAĞLARI" },
      { value: "yeast", label: "MAYA" },
      { value: "knitting_yarns", label: "ÖRGÜ İPLERİ" },
      { value: "special_dietary_foods", label: "ÖZEL BESLENME AMAÇLI GIDALAR" },
      { value: "jam_marmalade_jelly", label: "REÇEL, MARMELAT VE JÖLE" },
      { value: "paste_sauce", label: "SALÇA" },
      { value: "vinegar", label: "SİRKE" },
      { value: "sauces", label: "SOSLAR" },
      { value: "milk_and_dairy", label: "SÜT VE SÜT ÜRÜNLERİ" },
      { value: "confectionery", label: "ŞEKERLİ MAMULLER" },
      { value: "grain", label: "TAHIL" },
      { value: "cleaning_agents", label: "TEMİZLİK MADDELERİ" },
      { value: "cleaning_products", label: "TEMİZLİK ÜRÜNLERİ" },
      { value: "pickles", label: "TURŞU" },
      { value: "salt", label: "TUZ" },
      { value: "flour_and_flour_products", label: "UN VE UNLU MAMULLER" },
      { value: "varnish_and_polishes", label: "VERNİK VE CİLALAR" },
      { value: "olives", label: "ZEYTİN" }
    ]
  },
  { 
    value: "paper_products", 
    label: "KAĞIT ÜRÜNLERİ",
    subcategories: [
      { value: "diapers", label: "ÇOCUK BEZİ" },
      { value: "other", label: "DİĞER" },
      { value: "breast_pads", label: "GÖĞÜS PEDİ" },
      { value: "sanitary_pads", label: "HİJYENİK PED" },
      { value: "tampons", label: "TAMPON" }
    ]
  },
  { 
    value: "stationery", 
    label: "KIRTASİYE",
    subcategories: [
      { value: "tape", label: "BANT" },
      { value: "lunch_box", label: "BESLENME ÇANTASI" },
      { value: "coloring_materials", label: "BOYA KALEMLERİ VE BOYA MALZEMELERİ" },
      { value: "ruler", label: "CETVEL" },
      { value: "notebooks_paper", label: "DEFTERLER VE KAĞIT MALZEMELER" },
      { value: "other_products", label: "DİĞER ÜRÜNLER" },
      { value: "pencil_case", label: "KALEM KUTUSU" },
      { value: "pens_notebooks_plastic", label: "KALEMLER VE DEFTERLER (PLASTİK KISIMLAR)" },
      { value: "pencil_sharpener", label: "KALEMTIRAŞ" },
      { value: "packing_tape", label: "KOLİ BANDI," },
      { value: "scissors", label: "MAKAS" },
      { value: "school_bag", label: "OKUL ÇANTASI" },
      { value: "pastel_paint_case", label: "PASTEL BOYA ÇANTASI" },
      { value: "drawing_case", label: "RESİM ÇANTASI" },
      { value: "backpack", label: "SIRT ÇANTASI" },
      { value: "eraser", label: "SİLGİ" },
      { value: "spray_paints", label: "SPREY BOYALAR" },
      { value: "correction_products", label: "ŞERİT VE SIVI DÜZELTİCİ" },
      { value: "sticky_notes", label: "YAPIŞKAN NOTLUK" },
      { value: "glue", label: "YAPIŞTIRICI" },
      { value: "adhesives", label: "YAPIŞTIRICILAR" }
    ]
  },
  { 
    value: "chemical_and_organic_fertilizers", 
    label: "KİMYEVİ VE ORGANİK GÜBRELER",
    subcategories: [
      { value: "other_products", label: "DİĞER ÜRÜNLER" },
      { value: "enzyme_added_products", label: "ENZİM KATKILI ÜRÜNLER" },
      { value: "chemical_fertilizers", label: "KİMYEVİ GÜBRELER" },
      { value: "microbial_fertilizers", label: "MİKROBİYAL GÜBRELER" },
      { value: "organic_fertilizers", label: "ORGANİK GÜBRELER" },
      { value: "organo_mineral_fertilizers", label: "ORGANO MİNERAL GÜBRELER" },
      { value: "soil_conditioners", label: "TOPRAK DÜZENLEYİCİLER" }
    ]
  },
  { 
    value: "personal_protective_equipment", 
    label: "KİŞİSEL KORUYUCU DONANIMLAR",
    subcategories: [
      { value: "foot_leg_protection_shoes", label: "AYAK BACAK KORUYUCULAR - AYAKKABILAR" },
      { value: "foot_leg_protection_knee", label: "AYAK BACAK KORUYUCULAR - DİZ KORUYUCULAR" },
      { value: "foot_leg_protection_electrical", label: "AYAK BACAK KORUYUCULAR - ELEKTRİK RİSKLERİNE KARŞI KORUMA" },
      { value: "foot_leg_protection_safety_shoes", label: "AYAK BACAK KORUYUCULAR - İŞ GÜVENLİĞİ AYAKKABISI" },
      { value: "foot_leg_protection_chemical", label: "AYAK BACAK KORUYUCULAR - KİMYASAL VEYA RADYOAKTİF RİSKLER" },
      { value: "foot_leg_protection_protective_shoes", label: "AYAK BACAK KORUYUCULAR - KORUYUCU AYAKKABI" },
      { value: "foot_leg_protection_professional", label: "AYAK BACAK KORUYUCULAR - MESLEĞE ÖZEL KULLANIM" },
      { value: "foot_leg_protection_special", label: "AYAK BACAK KORUYUCULAR - ÖZEL KULLANIM(SPOR AMAÇLI)" },
      { value: "foot_leg_protection_high_temp", label: "AYAK BACAK KORUYUCULAR - YÜKSEK SICAKLIK ORTAMI" },
      { value: "head_protection_helmets", label: "BAŞ KORUYUCULAR - BARETLER" },
      { value: "head_protection_bike_helmet", label: "BAŞ KORUYUCULAR - BİSİKLET KASKI" },
      { value: "head_protection_other", label: "BAŞ KORUYUCULAR - DİĞER BAŞ KORUYUCULAR" },
      { value: "head_protection_electrical", label: "BAŞ KORUYUCULAR - ELEKTRİK RİSKLERİ" },
      { value: "head_protection_high_temp", label: "BAŞ KORUYUCULAR - YÜKSEK SICAKLIK ORTAMI" },
      { value: "life_jackets", label: "CAN YELEKLERİ" },
      { value: "diving_suit", label: "DALGIÇ ELBİSESİ" },
      { value: "sea_swimmer_goggles", label: "DENİZ VEYA YÜZÜCÜ GÖZLÜKLERİ" },
      { value: "other_eye_protection", label: "DİĞER GÖZ KORUYUCULAR" },
      { value: "hand_arm_protection_low_temp", label: "EL KOL KORUYUCULAR - DÜŞÜK SICAKLIK ORTAMI" },
      { value: "hand_arm_protection_gloves", label: "EL KOL KORUYUCULAR - ELDİVEN" },
      { value: "hand_arm_protection_material_gloves", label: "EL KOL KORUYUCULAR - ELDİVEN(DERİ, KUMAŞ VEYA DİĞER MALZEMELERDEN İMAL EDİLMİŞ)" },
      { value: "hand_arm_protection_electrical", label: "EL KOL KORUYUCULAR - ELEKTRİK RİSKLERİ" },
      { value: "hand_arm_protection_mechanical", label: "EL KOL KORUYUCULAR - MEKANİK RİSKLER" },
      { value: "hand_arm_protection_professional", label: "EL KOL KORUYUCULAR - MESLEĞE ÖZEL KULLANIM" },
      { value: "hand_arm_protection_special", label: "EL KOL KORUYUCULAR - ÖZEL KULLANIM" },
      { value: "hand_arm_protection_high_temp", label: "EL KOL KORUYUCULAR - YÜKSEK SICAKLIK ORTAMI" },
      { value: "hand_arm_protection_chemical", label: "EL KOL KORUYUCULAR -KİMYASALLAR VE RADYOAKTİF RİSKLER" },
      { value: "gas_filter", label: "GAZ FİLTRESİ" },
      { value: "clothing_full_isolation", label: "GİYSİLER - ATMOSFERDEN TAM YALITIM" },
      { value: "clothing_low_temp", label: "GİYSİLER - DÜŞÜK SICAKLIK ORTAMI" },
      { value: "clothing_electrical", label: "GİYSİLER - ELEKTRİK RİSKLERİ" },
      { value: "clothing_work_clothes", label: "GİYSİLER - İŞ ELBİSESİ" },
      { value: "clothing_chemical", label: "GİYSİLER - KİMYASALLAR VE RADYOAKTİF RİSKLERE KARŞI" },
      { value: "clothing_mechanical", label: "GİYSİLER - MEKANİK RİSKLER" },
      { value: "clothing_radioactive", label: "GİYSİLER - RADYOAKTİF RİSKLER" },
      { value: "clothing_hot_parts", label: "GİYSİLER - SICAK PARÇALARIN İŞLENMESİ" },
      { value: "clothing_high_temp", label: "GİYSİLER - YÜKSEK SICAKLIK ORTAMI" },
      { value: "clothing_special", label: "GİYSİLER- ÖZEL KORUMA" },
      { value: "eye_protection", label: "GÖZ KORUYUCULAR" },
      { value: "eye_protection_sunglasses", label: "GÖZ KORUYUCULAR - GÜNEŞ GÖZLÜKLERİ" },
      { value: "eye_protection_welding", label: "GÖZ KORUYUCULAR - KAYNAK GÖZLÜKLERİ" },
      { value: "eye_protection_high_temp", label: "GÖZ KORUYUCULAR - YÜKSEK SICAKLIK ORTAMI" },
      { value: "hearing_protection", label: "İŞİTME KORUYUCULAR" },
      { value: "welding_gloves", label: "KAYNAKÇI ELDİVENİ" },
      { value: "welding_shield", label: "KAYNAKÇI SİPERİ" },
      { value: "reflective_vest", label: "REFLEKTİF YELEK" },
      { value: "respiratory_protection", label: "SOLUNUM KORUYUCULAR" },
      { value: "respiratory_protection_full_face", label: "SOLUNUM KORUYUCULAR - TAM YÜZ MASKESİ" },
      { value: "breathing_apparatus", label: "TENEFFÜS CİHAZLARI" },
      { value: "breathing_apparatus_parts", label: "TENEFFÜS CİHAZLARININ AKSAM, PARÇA VE AKSESUARLARI" },
      { value: "dust_filter", label: "TOZ FİLTRESİ" },
      { value: "dust_mask", label: "TOZ MASKESİ" },
      { value: "half_face_mask", label: "YARIM YÜZ MASKESİ" },
      { value: "fall_protection", label: "YÜKSEKTEN DÜŞMEYE KARŞI KORUYUCULAR" },
      { value: "fall_protection_safety_line", label: "YÜKSEKTEN DÜŞMEYE KARŞI KORUYUCULAR - EMNİYET HALATI" },
      { value: "fall_protection_height_work", label: "YÜKSEKTEN DÜŞMEYE KARŞI KORUYUCULAR - YÜKSEKTE ÇALIŞMA" },
      { value: "fall_protection_climbing", label: "YÜKSEKTEN DÜŞMEYE KARŞI KORUYUCULAR-DAĞCILIK TEÇHİZATLARI" },
      { value: "fall_protection_safety_belt", label: "YÜKSEKTEN DÜŞMEYE KARŞI KORUYUCULAR-EMNİYET KEMERİ" },
      { value: "fall_protection_energy_absorber", label: "YÜKSEKTEN DÜŞMEYE KARŞI KORUYUCULAR-ENERJİ ABSORPLAYICI" },
      { value: "face_protection", label: "YÜZ KORUYUCULAR" },
      { value: "face_protection_vehicles", label: "YÜZ KORUYUCULAR - MOTORLU ARAÇLAR" },
      { value: "swimming_aid_vest", label: "YÜZMEYE YARDIMCI YELEK" }
    ]
  },
  { 
    value: "cosmetics", 
    label: "KOZMETİKLER",
    subcategories: [
      { value: "baby_products", label: "BEBEK ÜRÜNLERİ" },
      { value: "other", label: "DİĞER" },
      { value: "teeth_whitener", label: "DİŞ BEYAZLATICI" },
      { value: "toothpaste", label: "DİŞ MACUNU" },
      { value: "shower_gel", label: "DUŞ JELİ" },
      { value: "eyeshadow", label: "FAR" },
      { value: "sun_products", label: "GÜNEŞ ÜRÜNLERİ" },
      { value: "wet_wipes", label: "ISLAK MENDİL" },
      { value: "henna_set", label: "KINA SETİ" },
      { value: "cologne", label: "KOLONYA" },
      { value: "creams", label: "KREMLER" },
      { value: "makeup_set", label: "MAKYAJ SETİ" },
      { value: "makeup_remover", label: "MAKYAJ TEMİZLEME ÜRÜNÜ" },
      { value: "mascara", label: "MASKARA" },
      { value: "mucous_membrane_products", label: "MUKOZ MEMBRANLARA UYGULANAN ÜRÜNLER" },
      { value: "nail_polish", label: "OJE" },
      { value: "perfume", label: "PARFÜM" },
      { value: "professional_use_products", label: "PROFESYONEL KULLANIM AMAÇLI ÜRÜNLER" },
      { value: "powder", label: "PUDRA" },
      { value: "lipstick", label: "RUJ" },
      { value: "soap", label: "SABUN" },
      { value: "hair_care_product", label: "SAÇ BAKIM ÜRÜNÜ" },
      { value: "hair_dye", label: "SAÇ BOYASI" },
      { value: "hair_cream", label: "SAÇ KREMİ" },
      { value: "hair_spray", label: "SAÇ SPREYİ" },
      { value: "shampoo", label: "ŞAMPUAN" },
      { value: "nail_products", label: "TIRNAK ÜRÜNLERİ" },
      { value: "body_cream", label: "VÜCUT KREMİ" },
      { value: "body_lotion", label: "VÜCUT LOSYONU" },
      { value: "face_paint", label: "YÜZ BOYASI" },
      { value: "face_cream", label: "YÜZ KREMİ" },
      { value: "face_mask", label: "YÜZ MASKESİ" }
    ]
  },
  { 
    value: "toys", 
    label: "OYUNCAKLAR",
    subcategories: [
      { value: "mouth_organs", label: "AĞIZ ORGLARI (MIZIKA)" },
      { value: "action_hero_vehicles", label: "AKSİYON KAHRAMANIN ARAÇLARI" },
      { value: "action_heroes", label: "AKSİYON KAHRAMANLARI" },
      { value: "action_sets", label: "AKSİYON SETLERİ" },
      { value: "toolboxes", label: "ALET KUTULARI (FONKSİYONEL)" },
      { value: "role_playing_tools", label: "ALETLER (ROLE YAPMAYA YÖNELİK)" },
      { value: "shopping_carts", label: "ALIŞ VERİŞ ARABALARI" },
      { value: "toy_blushes", label: "ALLIKLAR" },
      { value: "toy_cars", label: "ARABALAR (OYNANAN)" },
      { value: "toy_vehicles", label: "ARAÇLAR" },
      { value: "pull_back_vehicles", label: "ARKADAN ÇEKMELİ ARAÇLAR" },
      { value: "jump_ropes", label: "ATLAMA İPLERİ" },
      { value: "carousels_type_a", label: "ATLIKARINCALAR-A TİPİ ATLIKARINCA (DÖNER KOLTUKLAR)" },
      { value: "carousels_type_b", label: "ATLIKARINCALAR-B TİPİ ATLIKARINCA (KLASİK ATLIKARINCA) ATLIKARINCALAR-C TİPİ ATLIKARINCA (KENDİ ETRAFINDA DÖNEN MANTAR ŞEKİLLİ ATLIKARINCA, ASKILI ATLIKARINCA)" },
      { value: "carousels_type_c", label: "ATLIKARINCALAR-C TİPİ ATLIKARINCA (KENDİ ETRAFINDA DÖNEN MANTAR ŞEKİLLİ ATLIKARINCA, ASKILI ATLIKARINCA)" },
      { value: "carousels_type_d", label: "ATLIKARINCALAR-D TİPİ ATLIKARINCA (RAYLI ATLIKARINCA)" },
      { value: "carousels_type_e", label: "ATLIKARINCALAR-E TİPİ ATLIKARINCA (DEV DÖNER DİSKLER)" },
      { value: "badminton_sets", label: "BADMİNTON SETLERİ (RAKETLİ)" },
      { value: "balloon_sets", label: "BALON SETLERİ" },
      { value: "bath_toys", label: "BANYO OYUNCAKLARI" },
      { value: "basketball_balls", label: "BASKETBOL TOPLARI" },
      { value: "baby_toys", label: "BEBEK OYUNCAKLARI" },
      { value: "skill_development_toys", label: "BECERİ GELİŞTİRME OYUNCAKLARI" },
      { value: "cribs_and_play_cribs", label: "BEŞİKLER VE OYUN BEŞİKLERİ" },
      { value: "cloth_dolls", label: "BEZ BEBEKLER" },
      { value: "educational_computer_games", label: "BİLGİSAYAR (ÖĞRETİCİ) OYUNLARI" },
      { value: "biology_sets", label: "BİYOLOJİ SETLER" },
      { value: "blocks", label: "BLOKLAR" },
      { value: "boxing_gloves", label: "BOKS ELDİVENLERİ" },
      { value: "interlocking_beads", label: "BONCUKLAR (İÇ İÇE GİREN)" },
      { value: "coloring_tools", label: "BOYAMA ARAÇ GEREÇLERİ" },
      { value: "coloring_books", label: "BOYAMA KİTAPLARI" },
      { value: "coloring_crayons", label: "BOYAMA MUMLARI" },
      { value: "coloring_sets", label: "BOYAMA SETLERİ" },
      { value: "cd_player_sets", label: "CD ÇALAR SETLERİ" },
      { value: "skin_stickers", label: "CİLDE YAPIŞTIRILAN ÇIKARTMALAR" },
      { value: "tea_sets", label: "ÇAY SETLERİ" },
      { value: "rattles", label: "ÇINGIRAKLAR" },
      { value: "ride_on_cars", label: "ÇOCUK ARABALARI (ÜZERİNE OTURULUP SÜRÜLEN)" },
      { value: "childrens_bicycles", label: "ÇOCUK BİSİKLETLERİ" },
      { value: "childrens_tents", label: "ÇOCUK ÇADIRLARI (İÇİNE GİRİLEBİLEN)" },
      { value: "childrens_skates", label: "ÇOCUK PATENLERİ" },
      { value: "pottery_sets", label: "ÇÖMLEK SETLERİ" },
      { value: "typewriters", label: "DAKTİLOLAR (FONKSİYONEL)" },
      { value: "impact_reducing_playground_surfaces_loose", label: "DARBE AZALTICI OYUN ALANI ZEMİNLERİ-GEVŞEK TANELİ DOLGU MALZEMELERİ VE DOĞAL YÜZEYLER" },
      { value: "impact_reducing_playground_surfaces_manufactured", label: "DARBE AZALTICI OYUN ALANI ZEMİNLERİ-İMAL EDİLMİŞ ZEMİN DÜZENLEME ÜRÜNLERİ" },
      { value: "drums", label: "DAVULLAR" },
      { value: "other_toys", label: "DİĞER ÜRÜNLER" },
      { value: "sewing_machines", label: "DİKİŞ MAKİNELERİ" },
      { value: "sewing_sets", label: "DİKİŞ SETLERİ" },
      { value: "baby_teethers", label: "DİŞLİKLER (BEBEKLER İÇİN)" },
      { value: "domino_tiles", label: "DOMİNO TAŞLARI" },
      { value: "tattoo_stickers", label: "DÖVME ÇIKARTMALARI" },
      { value: "lip_glosses", label: "DUDAK PARLATICILAR" },
      { value: "shoes_for_tying_knots", label: "DÜĞÜM ATMAK İÇİN AYAKKABILAR" },
      { value: "electronic_learning_aids", label: "ELEKTRONİK ÖĞRENME TAKVİYELERİ" },
      { value: "electronic_sets", label: "ELEKTRONİK SETLER" },
      { value: "matching_games", label: "EŞLEŞTİRME OYUNLARI" },
      { value: "activity_mats", label: "ETKİNLİK DÖŞEMELERİ (YERE SERİLEN)" },
      { value: "activity_centers", label: "ETKİNLİK MERKEZLERİ" },
      { value: "doll_houses", label: "EVCİLİK EVLERİ" },
      { value: "play_pots_and_pans", label: "EVCİLİK KAP, TENCERE VE TAVALARI" },
      { value: "projectile_toys", label: "FIRLATMA CİHAZLI OYUNCAKLAR" },
      { value: "flutes", label: "FLÜTLER" },
      { value: "toy_cameras", label: "FOTOĞRAF MAKİNELERİ" },
      { value: "photo_sets", label: "FOTOĞRAF SETLERİ" },
      { value: "soccer_balls", label: "FUTBOL TOPLARI" },
      { value: "lacing_cards", label: "GEÇİRMELİ/BAĞLAMALI KARTLAR" },
      { value: "guitars", label: "GİTARLAR" },
      { value: "eye_shadows", label: "GÖZ FARLARI" },
      { value: "suspended_nets_3d", label: "HAVADA ASILI AĞLAR-3-BOYUTLU DÜZENLENMİŞ DÜZLEMSEL AĞ TOPLULUKLARI" },
      { value: "suspended_nets_planar", label: "HAVADA ASILI AĞLAR-DÜZLEMSEL AĞLAR" },
      { value: "launch_helicopters", label: "HELİKOPTERLER/FIRLATMA" },
      { value: "toy_hockey_sticks", label: "HOKEY SOPALARI (OYUNCAK)" },
      { value: "popup_books", label: "İÇİNDEN OYUNCAK ZIPLAYAN KİTAPLAR" },
      { value: "popup_toys", label: "İÇİNDEN OYUNCAK ZIPLAYAN OYUNCAKLAR" },
      { value: "audio_visual_tools", label: "İŞİTSEL/GÖRSEL ARAÇLAR" },
      { value: "functional_toys", label: "İŞLEVSEL OYUNCAKLAR" },
      { value: "push_pull_toys", label: "İTTİRMELİ-ÇEKTİRMELİ OYUNCAKLAR" },
      { value: "gymnastic_play_environments", label: "JİMNASTİK OYUN ORTAMLARI" },
      { value: "cableway_suspended", label: "KABLOLU TAŞIMA TESİSATLARI-ASILI TİP KABLOLU TAŞIMA TESİSATLARI" },
      { value: "cableway_seated", label: "KABLOLU TAŞIMA TESİSATLARI-OTURMA TİPİ KABLOLU TAŞIMA TESİSATLARI" },
      { value: "paper_dolls", label: "KAĞITTAN OYUNCAK BEBEKLER" },
      { value: "board_books", label: "KALIN YAPRAKLI KİTAPLAR" },
      { value: "carnival_makeup", label: "KARNAVAL MAKYAJLARI" },
      { value: "card_games", label: "KART OYUNLARI" },
      { value: "board_games", label: "KARTON ÜSTÜ OYUNLAR" },
      { value: "cassette_players", label: "KASET ÇALARLAR" },
      { value: "cassettes", label: "KASETLER" },
      { value: "castanets", label: "KASTANYETLER (AVUÇ İÇİNDE BİRBİRİNE VURULARAK ÇALINAN MÜZİK ALETİ)" },
    ]
  },
  { 
    value: "batteries_and_accumulators", 
    label: "PİL VE AKÜLER",
    subcategories: [
      { value: "button_batteries", label: "DÜĞME TİPİ PİLLER" },
      { value: "gel_batteries", label: "JEL AKÜLER" },
      { value: "lead_acid_batteries", label: "KURŞUN ASİT AKÜLER" },
      { value: "dry_batteries", label: "KURU AKÜLER" },
      { value: "primary_batteries", label: "PRİMER PİLLER" },
      { value: "secondary_batteries", label: "SEKONDER PİLLER" }
    ]
  },
  { 
    value: "textile", 
    label: "TEKSTİL",
    subcategories: [
      { value: "baby_clothing", label: "BEBEK GİYİM" },
      { value: "wristband", label: "BİLEK BANDI" },
      { value: "direct_skin_contact_textiles", label: "CİLDE DİREKT TEMAS EDEN TEKSTİL ÜRÜNLERİ" },
      { value: "wallet", label: "CÜZDAN" },
      { value: "bed_sheets", label: "ÇARŞAFLAR" },
      { value: "childrens_clothing", label: "ÇOCUK GİYİM" },
      { value: "other_textile_products", label: "DİĞER ÜRÜNLER" },
      { value: "gloves", label: "ELDİVEN" },
      { value: "clothing_items", label: "GİYİM EŞYALARI" },
      { value: "towel", label: "HAVLU" },
      { value: "paper_and_leather_items", label: "KAĞITTAN VE DERİDEN EŞYA" },
      { value: "belt", label: "KEMER" },
      { value: "watch_strap", label: "KOL SAATİ KAYIŞI" },
      { value: "cushions", label: "MİNDERLER" },
      { value: "textile_leather_furniture_parts", label: "MOBİLYALARIN TEKSTİL VE DERİ İÇEREN BÖLÜMLERİ" },
      { value: "yarn_fabric_for_end_user", label: "NİHAİ KULLANICININ KULLANIMINA YÖNELİK İPLİK VE KUMAŞ" },
      { value: "school_clothing", label: "OKUL GİYİM EŞYALARI" },
      { value: "headband", label: "SAÇ BANDI" },
      { value: "chair_cover", label: "SANDALYE ÖRTÜSÜ" },
      { value: "hat", label: "ŞAPKA" },
      { value: "sleeping_bags", label: "UYKU TULUMLARI" },
      { value: "bed", label: "YATAK" }
    ]
  },
  { 
    value: "telecommunications_equipment", 
    label: "TELSİZ VE/VEYA TELEKOMÜNİKASYON TERMİNAL EKİPMANLARI",
    subcategories: [
      { value: "wifi_24ghz_devices", label: "2.4 GHZ Wİ-Fİ CİHAZLAR" },
      { value: "access_point_device", label: "Access Point Cihazı" },
      { value: "amateur_radio_device", label: "AMATÖR TELSİZ CİHAZI" },
      { value: "search_rescue_radio_device", label: "ARAMA KURTARMA TELSİZ CİHAZI (SART)" },
      { value: "base_station", label: "BAZ İSTASYONU (GSM, IMT, VB.)" },
      { value: "baby_monitors", label: "BEBEK İZLEME CİHAZLARI (40 MHZ VE 2.4 GHZ )" },
      { value: "bluetooth_devices", label: "BLUETOOTH ÖZELLİKLİ CİHAZLAR" },
      { value: "marine_radar_device", label: "DENİZ RADAR CİHAZI" },
      { value: "low_power_fm_transmitter", label: "DÜŞÜK GÜÇLÜ FM VERİCİSİ" },
      { value: "industrial_remote_control_devices", label: "ENDÜSTRİYEL UZAKTAN KUMANDA CİHAZLARI" },
      { value: "epirp_device", label: "EPIRP (ACİL DURUM KONUM BELİRTECİ) CİHAZI" },
      { value: "fax_modem_router_devices", label: "FAX/MODEM/ ROUTER CİHAZLARI" },
      { value: "fct_device", label: "FCT (FİXED CELLULAR TERMİNAL) CİHAZI" },
      { value: "wearable_devices", label: "GİYİLEBİLİR CİHAZLAR (AKILLI SAAT, BİLEKLİK VB.)" },
      { value: "gps_receivers_tracking_devices", label: "GPS ALICI VE TAKİP CİHAZLARI" },
      { value: "hf_ssb_land_radio_device", label: "HF/SSB KARA TELSİZ CİHAZI" },
      { value: "cellular_communication_module", label: "HÜCRESEL HABERLEŞME (GSM, IMT VB.) MODÜLÜ" },
      { value: "cellular_terminal_device", label: "HÜCRESEL HABERLEŞME TERMİNAL CİHAZI (GSM, IMT VB.)" },
      { value: "inmarsat_devices", label: "INMARSAT CİHAZLARI" },
      { value: "ip_phone", label: "IP TELEFON" },
      { value: "wired_analog_phone", label: "KABLOLU ANALOG TELEFON (PSTN)" },
      { value: "wireless_alarm_security_systems", label: "KABLOSUZ ALARM VE GÜVENLİK SİSTEMLERİ CİHAZLARI" },
      { value: "wireless_keyboard_mouse_headphones", label: "KABLOSUZ KLAVYE, MOUSE, KULAKLIK, MİKROFON, KAMERA CİHAZLARI" },
      { value: "wireless_well_automation_device", label: "KABLOSUZ KUYU OTOMASYON CİHAZI (SADECE TÜRKİYE'DE ÜRETİLİYOR)" },
      { value: "wireless_lan_devices", label: "KABLOSUZ LAN CİHAZLARI (WLAN)" },
      { value: "wireless_meter_reading_systems", label: "KABLOSUZ SAYAÇ OKUMA SİSTEMLERİ (SADECE TÜRKİYE'DE ÜRETİLİYOR)" },
      { value: "wireless_audio_broadcast_device", label: "KABLOSUZ SES YAYIN CİHAZI" },
      { value: "wireless_signal_transmitter", label: "Kablosuz Sinyal Aktarıcı" },
      { value: "cordless_phone", label: "KABLOSUZ TELEFON (DECT)" },
      { value: "wireless_video_audio_conference_devices", label: "KABLOSUZ VİDEO-SES KONFERANS CİHAZLARI" },
      { value: "mf_hf_ssb_marine_radio_device", label: "MF/HF SSB DENİZ TELSİZ CİHAZI" },
      { value: "mobile_phone", label: "MOBİL TELEFON (GSM, IMT, VB.)" },
      { value: "model_aircraft_drone_remote_control", label: "MODEL UÇAK VE İNSANSIZ HAVA ARACI UZAKTAN KUMANDA SİSTEMLERİ" },
      { value: "pmr_446_low_power_handheld_radio", label: "PMR 446 ALÇAK GÜÇLÜ EL TELSİZ CİHAZI" },
      { value: "pos_terminal_device", label: "POS TERMİNAL CİHAZI (2G, 3G)" },
      { value: "radar_device", label: "RADAR CİHAZI" },
      { value: "radiolink", label: "RADYOLİNK" },
      { value: "rf_barcode_reader_devices", label: "RF BARKOD OKUYUCU CİHAZLAR" },
      { value: "tablet_computer", label: "TABLET BİLGİSAYAR (Wİ-Fİ, 2G, 3G VB.)" },
      { value: "telemetry_device", label: "TELEMETRİ CİHAZI" },
      { value: "tv_fm_radio_transmitter_devices", label: "TELEVİZYON VE FM RADYO VERİCİ CİHAZLARI" },
      { value: "uhf_data_modem_device", label: "UHF DATA MODEM CİHAZI" },
      { value: "satellite_communication_devices", label: "UYDU HABERLEŞME CİHAZLARI" },
      { value: "vhf_fm_marine_radios", label: "VHF / FM DENİZ TELSİZLERİ" },
      { value: "vhf_fm_air_radios", label: "VHF / FM HAVA TELSİZLERİ" },
      { value: "vhf_uhf_fm_land_radio_device", label: "VHF-UHF FM KARA TELSİZ CİHAZI" }
    ]
  },
]; 